# Generated by Django 4.2.9 on 2026-02-06 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('agriculture', 'Agriculture'), ('services', 'Services'), ('logistics', 'Logistics'), ('ecommerce', 'E-commerce')], max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to='financial_data/%Y/%m/')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Financial Data',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='IndustryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50, unique=True)),
                ('avg_current_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_gross_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_net_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_debt_to_equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_inventory_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_receivables_days', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_roa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_roe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_revenue_growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('investor', 'Investor Report'), ('lender', 'Lender Report'), ('board', 'Board Report'), ('comprehensive', 'Comprehensive Report')], max_length=20)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('language', models.CharField(default='en', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.company')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cost_optimization', 'Cost Optimization'), ('working_capital', 'Working Capital'), ('financial_product', 'Financial Product'), ('compliance', 'Compliance'), ('general', 'General')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('implementation_effort', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.company')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('best', 'Best Case'), ('base', 'Base Case'), ('worst', 'Worst Case')], max_length=10)),
                ('forecast_months', models.IntegerField()),
                ('revenue_forecast', models.JSONField()),
                ('expense_forecast', models.JSONField()),
                ('cash_flow_forecast', models.JSONField()),
                ('assumptions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receivables_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payables_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_flow_stability', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_conversion_cycle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('health_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.company')),
                ('financial_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.financialdata')),
            ],
            options={
                'verbose_name_plural': 'Financial Metrics',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_rating', models.CharField(choices=[('AAA', 'AAA - Excellent'), ('AA', 'AA - Very Good'), ('A', 'A - Good'), ('BBB', 'BBB - Adequate'), ('BB', 'BB - Moderate Risk'), ('B', 'B - High Risk'), ('C', 'C - Very High Risk')], max_length=5)),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cash_flow_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('debt_servicing_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('concentration_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('compliance_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recommended_tenure_months', models.IntegerField(blank=True, null=True)),
                ('probability_of_stress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_factors', models.JSONField(default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessments', to='core.company')),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessment', to='core.financialmetrics')),
            ],
            options={
                'verbose_name_plural': 'Credit Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
